e-commerce/order/urls.py
from django.urls import path
from order import views


urlpatterns = [
    path('place-order/', views.place_order, name='place-order'),
    path('payment/', views.payment, name='payment'),
    path('order-complete/', views.order_complete, name='order-complete'),
]

e-commerce/the_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from the_shop import views
from django.conf.urls.static import static
from django.conf import settings
from marketplace import views as marketplace_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('account.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('cart/', marketplace_views.cart, name='cart'),
    path('search/', marketplace_views.search, name='search'),
    path('checkout/', marketplace_views.checkout, name='checkout'),
    path('order/', include('order.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e-commerce/account/forms.py
from django import forms
from account.models import User, UserProfile
from account.validators import allow_only_images_validator


class UserSignupForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'first name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'last name'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'confirm password'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(UserSignupForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control my-2'

    def clean(self):
        cleaned_data = super(UserSignupForm, self).clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            raise forms.ValidationError('Passwords do not match.')


class UserProfileForm(forms.ModelForm):
    profile_image = forms.FileField(widget=forms.FileInput(attrs={'placeholder': 'profile image', 'style': 'padding-top: 0rem; line-height: 3.2;'}), validators=[allow_only_images_validator])
    cover_image = forms.FileField(widget=forms.FileInput(attrs={'placeholder': 'cover image', 'style': 'padding-top: 0rem; line-height: 3.2;'}), validators=[allow_only_images_validator])
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'address'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'city'}))
    state = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'state'}))
    country = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'country'}))
    pin_code = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'pin code'}))
    latitude = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'latitude', 'readonly': 'readonly'}))
    longitude = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'longitude', 'readonly': 'readonly'}))

    class Meta:
        model = UserProfile
        fields = ['profile_image', 'cover_image', 'address', 'city', 'state', 'country', 'pin_code', 'latitude', 'longitude']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control my-2'


class UserInfoForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'first name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'last name'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'phone'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone']

    def __init__(self, *args, **kwargs):
        super(UserInfoForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control my-2'

e-commerce/order/forms.py
from django import forms
from order.models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'first name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'last name'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'phone'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'email'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'address'}))
    city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'city'}))
    state = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'state'}))
    country = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'country'}))
    pin_code = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'pin code'}))

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'email', 'address', 'city', 'state', 'country', 'pin_code']

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control my-2'

e-commerce/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'images/logo/logo.png' %}" rel="icon" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- START css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
      <link rel="stylesheet" href="{% static 'font/bootstrap-icons.css' %}">
      <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
    <!-- END css -->
    <!-- START js -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=USD"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
      <script>
        $(document).ready( function () {
          $('#myTable').DataTable();
        });
      </script>
      {% if '/' == request.path or '/vendor-profile/' in request.path %}
        <script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_API_KEY }}&libraries=places&callback=initAutoComplete" defer></script>
      {% endif %}
      <script src="{% static 'js/sweetalert2@11.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
    <!-- END js -->
  </head>
  <body>
    {% include 'includes/nav.html' %}
    {% block content %}{% endblock content %}
    {% include 'includes/alert-messages.html' %}
    {% include 'includes/footer.html' %}
  </body>
</html>

e-commerce/templates/home.html
{% extends 'base.html' %}
{% block title %}The Shop{% endblock title %}
{% block content %}
  <div class="container-fluid">
    {% include 'includes/carousel.html' %}
    <div class="container-fluid my-2">
      <div class="container bg-dark rounded-pill shadow" style="width: 80%;">
        <nav class="navbar">
          <form class="container-fluid" action="{% url 'search' %}" method="GET">
            <div class="row input-group g-2">
              <div class="col-md-5">
                <input type="text" name="q" class="form-control" placeholder="product, category, vendor">
              </div>
              <div class="col-md-5">
                <div class="select-location">
                  <input type="text" name="address" class="form-control" id="id_address" placeholder="search by location*" required>
                  <input type="hidden" name="lat" value="" id="id_latitude">
                  <input type="hidden" name="lng" value="" id="id_longitude">
                </div>
              </div>
              <div class="col-md-1">
                <select class="form-control" name="radius" id="radius" required>
                  <option value="" selected>radius</option>
                  <option value="1">1km</option>
                  <option value="2">2km</option>
                  <option value="3">3km</option>
                  <option value="4">4km</option>
                  <option value="5">5km</option>
                  <option value="10">10km</option>
                  <option value="15">15km</option>
                  <option value="25">25km</option>
                  <option value="50">50km</option>
                  <option value="75">75km</option>
                  <option value="100">100km</option>
                </select>
              </div>
              <div class="col-md-1">
                <button class="btn btn-dark rounded-pill"><i class="bi bi-search"></i></button>
              </div>
            </div>
          </form>
        </nav>
      </div>
      <h2>Vendors</h2><hr>
      <div class="row">
        {% for vendor in vendors %}
          <div class="col-md-4">
            <div class="card shadow-sm text-bg-dark my-2">
              <img src="{{ vendor.user_profile.cover_image.url }}" class="card-img" width="100%" alt="vendor cover image" style="filter: brightness(40%);">
              <div class="card-img-overlay">
                <div class="row">
                  <div class="col-md-2 text-center">
                    <a href="{% url 'vendor-details' vendor.slug %}"><img src="{{ vendor.user_profile.profile_image.url }}" height="60px" width="60px" class="rounded-pill" alt="vendor logo"></a>
                  </div>
                  <div class="col-md-10">
                    <a href="{% url 'vendor-details' vendor.slug %}" class="text-white" style="text-decoration: none;"><h5 class="card-title">{{ vendor.name }}</h5></a>
                    {% if vendor.is_open %}
                      <span class="badge bg-success-subtle border border-success-subtle text-success-emphasis rounded-pill">Open</span>
                    {% else %}
                      <span class="badge bg-danger-subtle border border-danger-subtle text-danger-emphasis rounded-pill">Close</span>
                    {% endif %}
                    {% if vendor.kms %}
                      <span class="badge bg-info-subtle border border-info-subtle text-info-emphasis rounded-pill text-start"><small>{{ vendor.kms }} km away</small></span><br>
                    {% endif %}
                    {% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
                      <span><i class="bi bi-geo-alt"></i> {{ vendor.user_profile.city }}, {{ vendor.user_profile.state }} - {{ vendor.user_profile.pin_code }}</span>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}