Book-Sharing/accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_view

from .views import (
    CreateUserView,
    profile_page,
    user_update,
    change_password,
    UserDetailView,
)  # UserProfileView # CreateDoneView

app_name = "accounts"

urlpatterns = [
    path("create/", CreateUserView.as_view(), name="create_account"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/", user_update, name="update_account"),
    # path('profile/', UserProfileView.as_view(), name='user_profile'),
    path("profile/", profile_page, name="user_profile"),
    path("change-password/", change_password, name="change_password"),
    # generic views
    # path('', include('django.contrib.auth.urls')),
    path("login/", auth_view.LoginView.as_view(), name="login"),
    path(
        "logout/",
        auth_view.LogoutView.as_view(),
        name="logout",
        kwargs={"next_page": "/"},
    ),
]

Book-Sharing/books/urls.py
from django.urls import path
from django.views import generic
from .views import (
    BookListView,
    BookDetailView,
    BookUpdateView,
    delete_book,
    user_booklist,
    user_booklist_update,
    BookCreateView,
    ReviewCreateView,
    review_update_view,
)

app_name = "books"

urlpatterns = [
    path("", BookListView.as_view(), name="books"),
    path("create/", BookCreateView.as_view(), name="create"),
    path("review-create/", ReviewCreateView.as_view(), name="review_create"),
    path("<slug>/review-update/", review_update_view, name="review_update"),
    path(
        "recommendations/",
        generic.TemplateView.as_view(template_name="books/recommendation.html"),
        name="recommendation",
    ),
    path("<slug>/detail/", BookDetailView.as_view(), name="detail"),
    path("<slug>/update/", BookUpdateView.as_view(), name="update"),
    path("<slug>/delete/", delete_book, name="delete"),
    path("user-booklist/", user_booklist, name="user_booklist"),
    path("user/booklist/update/", user_booklist_update, name="user_booklist_update"),
]

Book-Sharing/djBooks/urls.py
from django.contrib import admin
from django.views.generic import TemplateView
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_view

# from django.conf.urls import include # 2 new line
from rest_framework.authtoken.views import obtain_auth_token  # 11

from accounts.forms import EmailValidationOnForgotPassword

urlpatterns = [
    path("", include("pages.urls", namespace="pages")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("searchs/", include("searchs.urls", namespace="searchs")),
    # path('api/books/', include('books.api.urls', namespace="api-books")),
    # path('admin/', admin.site.urls),
    # path('api/', include('books.api.urls')), # 3 new line
    path("auth/", obtain_auth_token),  # 11
    # path('', TemplateView.as_view(template_name='react.html')),
    # path('walking', TemplateView.as_view(template_name='walking.html')),
    # re_path(r'^books/', TemplateView.as_view(template_name='react.html')),
    # path('api/books/', include('books.api.urls', namespace='api-books')),
    path("books/", include("books.urls", namespace="books")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
    path("admin/", admin.site.urls),
    # generic views
    # path('', include('django.contrib.auth.urls')),
    path(
        "password-reset/",
        auth_view.PasswordResetView.as_view(
            form_class=EmailValidationOnForgotPassword,
            template_name="registration/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_view.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_view.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_view.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Book-Sharing/pages/urls.py
from django.urls import path

from .views import ContactCreateView, NewsAndEventList
from django.views import generic

app_name = 'pages'

urlpatterns = [
    # path('', home_view, name='home'),
    path('', generic.TemplateView.as_view(template_name='pages/index.html'), name='home'),
    path('about/', generic.TemplateView.as_view(template_name='pages/about.html'), name='about'),
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('news-and-events/', NewsAndEventList.as_view(), name='news_events'),
]

Book-Sharing/pages/models.py
from django.db import models
from django.db.models import Q

News = "News"
Events = "Events"

POSTED_AS = (
    (News, "News"),
    (Events, "Events")
)


class NewsAndEventManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(summary__icontains=query)| 
                         Q(posted_as__icontains=query)| 
                         Q(timestamp__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class NewsAndEvent(models.Model):
    title = models.CharField(max_length=120, null=True)
    summary = models.TextField(blank=True)
    posted_as = models.TextField(choices=POSTED_AS, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = NewsAndEventManager()

    def __str__(self):
        return self.title


class Contact(models.Model):
    first_name = models.CharField(max_length=120, null=True)
    last_name = models.CharField(max_length=120, null=True)
    email = models.EmailField(null=True, blank=True)
    # subject = models.CharField(max_length=120, null=True)
    message = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

Book-Sharing/templates/pages/about.html
{% extends 'base.html' %}
{% block title %}About Us | Fidel{% endblock title %}
{% load static %}

{% block content %}
<br><br><br><br>
<div class="container">
    <div class="title-1">About Fidele</div><br>
    <div class="card p-3" style="box-shadow: 0 5px 0 5px rgba(0,0,0,.3);">
        <p class="lead">
            Fidel Books is a Platform that allows you to connect with other like
            minded readers, swap books, discuss, comment and review books.
        </p>
    </div>
</div>
<br><br><br><br>
{% endblock %}

Book-Sharing/templates/pages/contact.html
{% extends 'base.html' %}
{% block title %}Contact Us | ACO{% endblock title %}
{% load static %}

{% block content %}
<style>
  .container {
    max-width: 960px;
  }

  .lh-condensed {
    line-height: 1.25;
  }
</style>

<br><br><br>

<div class="container">

  {% if messages %}
  {% for message in messages %}
  {% if message.tags == 'error' %}
  <div class="alert alert-danger">
    <i class="fas fa-exclamation-circle"></i> {{ message }}
  </div>
  {% else %}
  <div class="alert alert-success">
    <i class="fas fa-check-circle"></i> {{ message }}
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}

  <h1 class="display-4">Contact US</h1>
  <p class="lead text-muted">Make contact with us. Get news, updates, and any activities from us quickly.
    Once you submit the form, we will contact you by email as soon as possible.</p>
</div>

<div class="container">
  <div class="row">
    <!-- <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Contact Info</span>
      </h4>
      <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Email</h6>
            <small class="text-muted">acoethiopia@gmail.com</small>
          </div>
          <span class="text-muted"><i class="fas fa-envelope"></i></span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Mobile No.</h6>
            <small class="text-muted">+(251) 93-413-3437</small>
          </div>
          <span class="text-muted"><i class="fas fa-phone"></i></span>
        </li>
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">Address</h6>
            <small class="text-muted">Adama, Ethiopia</small>
          </div>
          <span class="text-muted"><i class="fas fa-location-arrow"></i></span>
        </li>
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Postal code</h6>
            <small>None</small>
          </div>
          <span class="text-success">PC</span>
        </li>
      </ul>
    </div> -->

    <div class="col-md-8 order-md-1">
      <form class="needs-validation" method="POST" action="" novalidate>{% csrf_token %}
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="first_name">First name</label>
            <input type="text" class="form-control" id="firstName" name="first_name" placeholder="" value="" required>
            <div class="invalid-feedback">
              Valid first name is required.
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <label for="last_name">Last name</label>
            <input type="text" class="form-control" id="lastName" name="last_name" placeholder="" value="" required>
            <div class="invalid-feedback">
              Valid last name is required.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="email">Email</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-envelope"></i></span>
            </div>
            <input type="email" class="form-control" id="email" name="email" placeholder="you@example.com">
            <div class="invalid-feedback">
              Please enter a valid email address for shipping updates.
            </div>
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Message</label>
          <textarea class="form-control" name="message" id="textarea" cols="30" rows="10"
            placeholder="your message..."></textarea>
          <div class="invalid-feedback">
            Please enter your message.
          </div>
        </div>

        <button class="btn btn-primary btn-lg btn-block mb-5" type="submit" style="border-radius: 1px;">Send
          message</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
<script>
  // Example starter JavaScript for disabling form submissions if there are invalid fields
  (function () {
    'use strict'

    window.addEventListener('load', function () {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation')

      // Loop over them and prevent submission
      Array.prototype.filter.call(forms, function (form) {
        form.addEventListener('submit', function (event) {
          if (form.checkValidity() === false) {
            event.preventDefault()
            event.stopPropagation()
          }
          form.classList.add('was-validated')
        }, false)
      })
    }, false)
  }())
</script>
{% endblock js %}

Book-Sharing/templates/pages/index.html
{% extends 'base.html' %}
{% block title %} Fidele Books - Explore your favorite book {% endblock title %}

{% load static %}
{% load ratings %}

{% block content %}

<style>
    /* .hero {filter: brightness(50%)} */
    .hero {
        min-height: 50vh;
        position: relative;
    }

    .hero::before {
        content: '';
        position: absolute;
        display: block;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, .5);
        z-index: 1;
    }

    .hero .bg-img {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
</style>

<div class="hero bg-dark">
    <img src="{% static 'img/bg-1.jpg' %}" class="bg-img" alt="">

    <style>
        .anim-text {
            width: 100%;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translateX(-50%) translateY(-50%);
            z-index: 10;
        }

        .anim-text .text-wrapper {
            font-size: 55px;
            letter-spacing: -4px;
            font-weight: 700;
            color: #7e2ea0;
            text-align: center;
            text-shadow: -1px 1px 0 #fff, 1px 1px 0 #fff, 1px -1px 0 #fff, -1px -1px 0 #fff;
        }

        @media (max-width:700px) {
            .anim-text .text-wrapper {
                font-size: 2.5em;
            }
        }

        .cssanimation,
        .cssanimation span {
            animation-duration: 1s;
            animation-fill-mode: both;
        }

        .cssanimation span {
            display: inline-block
        }

        .leRotateSkateInLeft span {
            animation-name: leRotateSkateInLeft
        }

        @keyframes leRotateSkateInLeft {
            from {
                transform: scaleX(0.2) translateX(-100px);
                opacity: 0;
            }
        }
    </style>

    <div class="anim-text">
        <div class="container">
            <h1 class="text-wrapper cssanimation sequence leRotateSkateInLeft">Books were my pass to personal freedom
            </h1>
            <h1 class="cssanimation leRotateSkateInLeft random" style="margin-left: 100px; font-size: 20px;">- Oprah
                Winfrey</h1>
        </div>
    </div>

</div>

<main role="main" class="container-fluid">
    <div class="row">
        <div class="col-md-8 d-flex mr-auto p-0" style="box-shadow: 0 40px 30px -20px #d6d6d6;">
            <div class="col-md-4 p-0">
                <img src="{% static 'img/books-3.jpg' %}" alt="" width="100%">
            </div>
            <div class="col-md-7 text-muted py-2">
                <h3>About Fidele</h3>
                <p class="pb-1">
                    Fidel Books is a Platform that allows you to connect with other like
                    minded readers, swap books, discuss, comment and review books.
                </p>
                Find your favorite book.
            </div>
        </div>
        {% if request.user.is_authenticated %}
        {% else %}
        <div class="col-md-4 mr-0" style="margin-top: -100px; z-index: 10;">
            <div class="card p-3" style="box-shadow: 0 80px 30px -60px #d6d6d6;">

                <form id="account-create-form" action="{% url 'accounts:create_account' %}" method="POST">
                    {% csrf_token %}
                    <input type="email" name="email" maxlength="255" class="form-control" required="" id="id_email"
                        placeholder="Email Address">
                    <span id="form-email-error"></span><br>
                    <input type="password" name="password" maxlength="128" class="form-control" required=""
                        id="id_password" placeholder="New Password">
                    <br>
                    <button id="form-submit-btn" class="btn btn-lg btn-success" type="submit">Create account</button>
                </form>

            </div>
        </div>
        {% endif %}
    </div>

    <br><br>
    <div class="container">
        <div class="row">
            <style>
                p {
                    padding: 0;
                    margin: 0;
                }
            </style>
            <!-- <div class="col-md-3">
                <img src="{% static 'img/favicon.png' %}" alt="" width="250px">
            </div> -->
            <div class="col-md-9"><br>
                <h2>Books for you</h2>
                <p class="text-warning"> Improve recommendations by adding books to your booklist and rating books.</p>

                {% include 'snippets/recommendation.html' %}
            </div>
        </div>
    </div>

    <div class="row py-5 my-0 bg-blue-black text-light">
        <div class="col-md-4">
            <div class="d-flex">
                <h1 class="counter">&#x2170;</h1>
                <h1 class="display-5">Read Books</h1>
            </div>
            <p style="position: relative;">
            <h1 class="quet">&#8220;</h1>
            Read your favorite books. We collect the most interesting books that everyone can read and
            gain some knowledge. Feel free to access anything and ask the authors.
            </p>
        </div>
        <div class="col-md-4">
            <div class="d-flex">
                <h1 class="counter">&#x2171;</h1>
                <h3 class="">Get Recommendations</h3>
            </div>
            <p style="position: relative;">
            <h1 class="quet">&#8220;</h1>
            We recommend books that may surprise you. Read the book you like and then we recommend books
            based on the genre of books you have read in the past. But this is done if you are logged in otherwise we
            recommend by highly rating book.
            </p>
        </div>
        <div class="col-md-4">
            <div class="d-flex">
                <h1 class="counter">&#x2172;</h1>
                <h1 class="display-5">Group Discussion </h1>
            </div>
            <p style="position: relative;">
            <h1 class="quet">&#8220;</h1>
            Select a book you want then choose a discussion topic or create your own and then discuss it with other
            readers. The topic should be based on the book you have chosen.
            </p>
        </div>
    </div>
</main>

{% endblock %}

{% block js %}

<script>
    // text animation
    window.onload = function () {
        animateSequence();
        animateRandom();
    };

    function animateSequence() {
        var a = document.getElementsByClassName('sequence');
        for (var i = 0; i < a.length; i++) {
            var $this = a[i];
            var letter = $this.innerHTML;
            letter = letter.trim();
            var str = '';
            var delay = 100;
            for (l = 0; l < letter.length; l++) {
                if (letter[l] != ' ') {
                    str += '<span style="animation-delay:' + delay + 'ms; -moz-animation-delay:' + delay + 'ms; -webkit-animation-delay:' + delay + 'ms; ">' + letter[l] + '</span>';
                    delay += 150;
                } else
                    str += letter[l];
            }
            $this.innerHTML = str;
        }
    }

    function animateRandom() {
        var a = document.getElementsByClassName('random');
        for (var i = 0; i < a.length; i++) {
            var $this = a[i];
            var letter = $this.innerHTML;
            letter = letter.trim();
            var delay = 70;
            var delayArray = new Array;
            var randLetter = new Array;
            for (j = 0; j < letter.length; j++) {
                while (1) {
                    var random = getRandomInt(0, (letter.length - 1));
                    if (delayArray.indexOf(random) == -1)
                        break;
                }
                delayArray[j] = random;
            }
            for (l = 0; l < delayArray.length; l++) {
                var str = '';
                var index = delayArray[l];
                if (letter[index] != ' ') {
                    str = '<span style="animation-delay:' + delay + 'ms; -moz-animation-delay:' + delay + 'ms; -webkit-animation-delay:' + delay + 'ms; ">' + letter[index] + '</span>';
                    randLetter[index] = str;
                } else
                    randLetter[index] = letter[index];
                delay += 80;
            }
            randLetter = randLetter.join("");
            $this.innerHTML = randLetter;
        }
    }

    function getRandomInt(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    // animate button
    // var formData = document.getElementById('account-create-form');
    // var submitBtn = document.getElementById('form-submit-btn');

    // formData.addEventListener('submit', () => {
    //     submitBtn.innerHTML = "<span class='spinner-border spinner-border-sm' role='status' aria-hidden='true'></span> Loading...";
    //     submitBtn.setAttribute("disabled", "");

    //     // disable inputes
    //     // formData.childNodes[3].disabled = true;
    //     // formData.childNodes[9].disabled = true;

    //     window.setTimeout(function () {
    //         // when asyncronous action is done, remove the spinner
    //         // re-enable button/fieldset
    //         submitBtn.innerHTML = "Create Account"
    //         submitBtn.removeAttribute("disabled", "");
    //         formData.childNodes[3].disabled = false;
    //         formData.childNodes[9].disabled = false;
    //     }, 4000);
    // }, false);
</script>

{% endblock js %}

Book-Sharing/templates/pages/newsandevent_list.html
{% extends 'base.html' %}
{% block title %}News & Events | Fidel{% endblock title %}
{% load static %}
{% load text_toggler %}

{% block content %}

<br><br><br><br><br><br>

<!-- news and events -->

<style>.more{display: none}</style>

<div class="site-section">
  <div class="container" style="max-width: 960px;">
    <h2 class="heading-title">NEWS & EVENTS</h2>
    <div class="title-line mb-3"></div>
    <p class="mb-5">
      The latest news and events.
    </p>
    <div class="row">

      {% for item in items %}
      <div class="col-md-6">
        <div class="card mb-4">
          <div class="card-body">
            <div class="card-title-wrapper">
              <b>{{ item.title|title }}</b>
              <small>{{ item.posted_as }}</small>
              <p><div class="text-muted">{{ item.timestamp|timesince }} ago</div></p>
            </div>
            {% get_first_word item.summary %}<span class="dots">...</span><span class="more">{% get_remain_word item.summary %}</span>
            <button class="read btn btn-warning">Read more</button>

          </div>

        </div>
      </div>
      {% empty %}
      <div class="alert alert-info mx-auto">No news and events yet.</div>
      {% endfor %}

      <div class="col-12 text-right see-more"><a href="{% url 'pages:news_events' %}">See more. . . <span>&raquo;</span></a></div>

    </div>
  </div>
</div>
<br><br><br><br>
{% endblock %}

{% block js %}
<script>
  $(document).ready(function(){
    $('.read').click(function(){
      $(this).prev().toggle();
      $(this).siblings('.dots').toggle();
      if($(this).text()=='Read more'){
        $(this).text('Read less');
      }
      else{
        $(this).text('Read more');
      };
    });
  });
</script>
{% endblock js %}